wandb:
  login: 
    key: "99975cd8f95af3ba68278d2484eb109af43a4a64" ### Login key / Don't change
  init: ### Ref: https://docs.wandb.ai/ref/python/init
    entity: "cmu_23f_iitp_smad_dfd" ### Your wandb profile name (=id)
    project: "[LSY] SmdaNet_AV" ### Dont't change
    save_code: true ### Don't change
    group: "" ### Don't change / Ref: https://docs.wandb.ai/guides/runs/grouping
    job_type: "train" ### "data-preprocess", "train", "test", "visualize" etc...
    tags: ["Base"] ### [Network, Size, etc...]
    name: "v1.0.7" ### "Network"_"Size"_"Version" | Version policy: v{Architecture change}_{Method/Block change}_{Layer/Minor change}
    notes: "build by lsy" ### Insert schanges(plz write details)
    dir: "./wandb" ### Don't change
    resume: "auto" ### Don't change
    reinit: false ### Don't change
    magic: null ### Don't change
    config_exclude_keys: [] ### Don't change
    config_include_keys: [] ### Don't change
    anonymous: null ### Don't change
    mode: "online" ### Don't change
    allow_val_change: true ### Don't change
    force: false ### Don't change
    sync_tensorboard: false ### Don't change
    monitor_gym: false ### Don't change
    config:
      dataset:
        data_path: "/home/lsy/laboratory/Research/idea4_MDFD/data"
      dataloader:
        batch_size: 64
        pin_memory: true
        num_workers: 12
      model:
        visual_shape: [64, 2, 3, 224, 244]
        audio_shape: [64, 2, 3, 224, 224]
        num_classes: 4
      criterion: ### Ref: https://pytorch.org/docs/stable/nn.html#loss-functions
        name: "CrossEntropyLoss" ### Choose a torch.nn's class(=attribute) e.g. ["CrossEntropyLoss", "MSELoss", "Custom", ...] / You can build your criterion :)
      optimizer: ### Ref: https://pytorch.org/docs/stable/optim.html#algorithms
        name: "AdamW" ### Choose a torch.optim's class(=attribute) e.g. ["Adam", "AdamW", "SGD", ...] / You can build your optimizer :)
        Adam: ### Add or modify instance & args using reference link
          lr: 1.0e-4
          weight_decay: 1.0e-2
        AdamW:
          lr: 1.0e-4
          weight_decay: 1.0e-2
        SGD:
          lr: 1.0e-4
          momentum: 0.9
          weight_decay: 1.0e-2
        Custom:
          custom_arg1:
          custom_arg2:
      scheduler: ### Ref(+ find "How to adjust learning rate"): https://pytorch.org/docs/stable/optim.html#algorithms
        name: "StepLR" ### Choose a torch.optim.lr_scheduler's class(=attribute) e.g. ["StepLR", "ReduceLROnPlateau", "Custom"] / You can build your scheduler :)
        StepLR: ### Add or modify instance & args using reference link
          step_size: 5
          gamma: 0.9
        ReduceLROnPlateau:
          mode: "min"
          min_lr: 1.0e-10
          factor: 0.9
          patience: 5
        Custom:
          custom_arg1:
          custom_arg2:
      engine:
        epoch: 200
        gpuid: "0" ### "0"(single-gpu) or "0, 1" (multi-gpu)